theme = "gruvbox"

[editor]
true-color = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
S-h = "goto_first_nonwhitespace" 
S-l = "goto_line_end"

C-a = ":write-all"

C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]

i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

u = ["undo", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]

"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

j = "move_line_down"
k = "move_line_up"

d = ["yank", "delete_selection"]
y = ["yank", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
p = ["paste_after", "flip_selections", "collapse_selection"]
P = ["paste_before", "flip_selections", "collapse_selection"]

[keys.insert]
"esc" = ["collapse_selection", "normal_mode"]

[keys.select]
C-j = "shrink_selection"
C-k = "expand_selection"

S-h = "goto_first_nonwhitespace"
S-l = "goto_line_end"

k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

d = ["yank", "delete_selection"]
y = ["yank", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
p = ["paste_after", "flip_selections", "collapse_selection"]
P = ["paste_before", "flip_selections", "collapse_selection"]

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
