﻿theme = "gruvbox"
  
[editor]
true-color = true

[keys.normal]
S-h = "goto_first_nonwhitespace" 
S-l = "goto_line_end"

C-S = ":write-all"
C-A = ":write"

C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]

i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

u = ["undo", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]

"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

j = "move_line_down"
k = "move_line_up"

[keys.insert]
C-space = "completion"
esc = ["collapse_selection", "normal_mode"]

[keys.select]
C-j = "shrink_selection"
C-k = "expand_selection"

S-h = "goto_first_nonwhitespace"
S-l = "goto_line_end"

i = "select_textobject_inner"
a = "select_textobject_around"

k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

d = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
p = "replace_selections_with_clipboard"

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
